### ISSUE TITLE
VerificationFailure: no public key

### ISSUE THREAD

**Issue by edips** [yan12125/python3-android#16]
Hi, I tried to build it with NDK 15 version on Manjaro, I got the error:
```
  File "/home/edip/workspace/pyotherside/python3-android/pybuild/util.py", line 99, in gpg_verify_file
    raise VerificationFailure(verify_result.status)
pybuild.util.VerificationFailure: no public key
```
Is it possible to fix it? Thanks.

**Comment by yan12125** [comment]
You can import all necessary PGP keys using https://github.com/yan12125/python3-android/blob/master/devscripts/import_pgp_keys.sh before building.

However, these scripts are currently broken. You may want to download previously built binaries at https://dl.chyen.cc/python3-android/.

**Comment by edips** [comment]
Thank you. I try to build it in order to run QML with Python using pyotherside. Qt doesn't work for Android for ndk 17+. When I couldn't build your python 3 repository,  I tried https://github.com/GRRedWings/python3-android this worked but now I couldn't build pyotherside for Android :)

**Comment by yan12125** [comment]
I've managed to fix all issues and scripts in this repo should work now. Note that the latest commit requires NDK r19 beta 1 or newer as it uses the new unified toolchain. If you have an older NDK, use 4095136d4615984ecf3da60b38a81e5fd29ae698.

**Comment by GRRedWings** [comment]
I'm trying to build with the latest, and I get the error below saying it's unable to run gpg.  I installed gnupg based on your instructions, but I'm wondering if I missed  step.
I have ANDROID_NDK and PYTHON in my path. I have Python 3.8 installed with homebrew.   I am trying to this on a Mac.  

Traceback (most recent call last):
  File "/usr/local/Cellar/python/HEAD-b6ef6f6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python/HEAD-b6ef6f6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Brian/python3-android-yan/pybuild/__main__.py", line 3, in <module>
    main()
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 60, in main
    build_package('python')
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 40, in build_package
    build_package(dep)
  File "/Users/Brian/python3-android-yan/pybuild/main.py", line 27, in build_package
    src.verify()
  File "/Users/Brian/python3-android-yan/pybuild/source.py", line 70, in verify
    gpg_verify_file(str(self.target) + self.sig_suffix, self.target,
  File "/Users/Brian/python3-android-yan/pybuild/util.py", line 89, in gpg_verify_file
    gpg = gnupg.GPG()
  File "/Users/Brian/Library/Python/3.8/lib/python/site-packages/gnupg.py", line 813, in __init__
    raise OSError(msg)
OSError: Unable to run gpg (gpg) - it may not be available.

**Comment by yan12125** [comment]
Hmm, can you run `gpg --version` from your terminal?

**Comment by GRRedWings** [comment]
It is unknown.  Like it's not installed.


python -m pip install --user python-gnupg

Installs it right?


--------------------------
Sent from my phone. Please forgive the short nature of the message, if
needed I will follow up with more details.

**Comment by yan12125** [comment]
Oh, I forget to mention that you need to install gnupg first.

This should work: `brew install gnupg`.
