### ISSUE TITLE
Error when building, issue with "io.py"

### ISSUE THREAD

**Issue by isaaclo123** [yan12125/python3-android#19]
When running make, make fails with this error

```
/home/isaac/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -shared -L/home/isaac/git/python3.8-android/build/sysroot/usr/lib -fuse-ld=lld -march=armv7-a    -Wl,--no-as-needed -o libpython3.so -Wl,-hlibpython3.so libpython3.8.so
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected.
ld.lld: warning: lld uses extended branch encoding, no object with architecture supporting feature detected.
ld.lld: warning: lld may use movt/movw, no object with architecture supporting feature detected.
/home/isaac/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -L/home/isaac/git/python3.8-android/build/sysroot/usr/lib -fuse-ld=lld -march=armv7-a    -pie -Xlinker -export-dynamic -o python Programs/python.o -L. -lpython3.8 -ldl  -lm   -lm 
_PYTHON_PROJECT_BASE=/home/isaac/git/python3.8-android/src/cpython _PYTHON_HOST_PLATFORM=linux-arm PYTHONPATH=./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata__linux_ python3.8 -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "./Lib/io.py", line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)
generate-posix-vars failed
make[1]: *** [pybuilddir.txt] Error 1
make[1]: Leaving directory `/home/isaac/git/python3.8-android/src/cpython'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/isaac/git/python3.8-android/pybuild/__main__.py", line 3, in <module>
    main()
  File "/home/isaac/git/python3.8-android/pybuild/main.py", line 52, in main
    build_package('python')
  File "/home/isaac/git/python3.8-android/pybuild/main.py", line 44, in build_package
    pkg.build()
  File "/home/isaac/git/python3.8-android/pybuild/packages/python.py", line 64, in build
    self.run(['make'])
  File "/home/isaac/git/python3.8-android/pybuild/package.py", line 108, in run
    self.source.run_in_source_dir(cmd, *args, **kwargs)
  File "/home/isaac/git/python3.8-android/pybuild/source.py", line 52, in run_in_source_dir
    return run_in_dir(cmd, self.source_dir, env, mode)
  File "/home/isaac/git/python3.8-android/pybuild/util.py", line 65, in run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
make: *** [all] Error 1
```

**Comment by yan12125** [comment]
```
 File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
```
This looks like the cause. You need the latest Python 3.8 interpreter when crossing building Python 3.8 for Android.

**Comment by isaaclo123** [comment]
The same issue is there with the python 3.8
```
/home/isaac/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -shared -L/home/isaac/git/python3.8-android/build/sysroot/usr/lib -fuse-ld=lld -march=armv7-a    -Wl,--no-as-needed -o libpython3.so -Wl,-hlibpython3.so libpython3.8.so
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected.
ld.lld: warning: lld uses extended branch encoding, no object with architecture supporting feature detected.
ld.lld: warning: lld may use movt/movw, no object with architecture supporting feature detected.
/home/isaac/Android/Ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang -L/home/isaac/git/python3.8-android/build/sysroot/usr/lib -fuse-ld=lld -march=armv7-a    -pie -Xlinker -export-dynamic -o python Programs/python.o -L. -lpython3.8 -ldl  -lm   -lm 
_PYTHON_PROJECT_BASE=/home/isaac/git/python3.8-android/src/cpython _PYTHON_HOST_PLATFORM=linux-arm PYTHONPATH=./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata__linux_ python3.8 -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "./Lib/io.py", line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)
generate-posix-vars failed
make[1]: *** [pybuilddir.txt] Error 1
make[1]: Leaving directory `/home/isaac/git/python3.8-android/src/cpython'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/isaac/git/python3.8-android/pybuild/__main__.py", line 3, in <module>
    main()
  File "/home/isaac/git/python3.8-android/pybuild/main.py", line 52, in main
    build_package('python')
  File "/home/isaac/git/python3.8-android/pybuild/main.py", line 44, in build_package
    pkg.build()
  File "/home/isaac/git/python3.8-android/pybuild/packages/python.py", line 64, in build
    self.run(['make'])
  File "/home/isaac/git/python3.8-android/pybuild/package.py", line 108, in run
    self.source.run_in_source_dir(cmd, *args, **kwargs)
  File "/home/isaac/git/python3.8-android/pybuild/source.py", line 52, in run_in_source_dir
    return run_in_dir(cmd, self.source_dir, env, mode)
  File "/home/isaac/git/python3.8-android/pybuild/util.py", line 65, in run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/usr/lib/python3.8/subprocess.py", line 348, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
make: *** [all] Error 1
```

**Comment by yan12125** [comment]
io.open_code is added 3 days ago: https://github.com/python/cpython/commit/b82e17e626f7b1cd98aada0b1ebb65cb9f8fb184. Please check if your Python 3.8 interpreter (e.g. /usr/bin/python3.8) is newer than that commit or not.

**Comment by isaaclo123** [comment]
Thank you, that seems to work.

**Comment by ankit-bhardwaj10** [comment]
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\python\lib\io.py", line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)

it again showing this help guys when im launching anaconda 3 prompt

**Comment by yan12125** [comment]
> it again showing this help guys when im launching anaconda 3 prompt

The Anaconda Python might cause an issue. Please build Python 3.9 from sources following https://github.com/yan12125/python3-android#prerequisites.

**Comment by ankit-bhardwaj10** [comment]
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
File "C:\python\lib\io.py", line 54, in
ImportError: cannot import name 'open_code' from 'io' (unknown location)

my device is windows 10

**Comment by yan12125** [comment]
> my device is windows 10

I wrote Linux in the documentation as only Linux is periodically tested. There were reports for successful builds on Windows (https://github.com/yan12125/python3-android/issues/18#issuecomment-476192901). You may need to find Windows-ports for tools mentioned in the documentation, though.

**Comment by reemamsharma** [comment]
Hi,

Getting this error while executing my code on Python 3.8
**Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\python38\Lib\io.py", line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)**


Please suggest a way to rectify this.

**Comment by yan12125** [comment]
> my code

Please don't ask general questions here. This is the issue tracker for python3-android.
