### ISSUE TITLE
make fails with SRE mismtach error?

### ISSUE THREAD

**Issue by ChillarAnand** [yan12125/python3-android#2]
```
Traceback (most recent call last):
  File "./setup.py", line 4, in <module>
    import sys, os, importlib.machinery, re, optparse
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/src/cpython/Lib/re.py", line 123, in <module>
    import sre_compile
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/src/cpython/Lib/sre_compile.py", line 19, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch
Makefile:583: recipe for target 'sharedmods' failed
make[1]: *** [sharedmods] Error 1
make[1]: Leaving directory '/home/chillaranand/projects/moriarty/tmp/python3-android/src/cpython'
Traceback (most recent call last):
  File "/home/chillaranand/.pyenv/versions/3.7-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chillaranand/.pyenv/versions/3.7-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/__main__.py", line 3, in <module>
    main()
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/main.py", line 39, in main
    build_package('python')
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/main.py", line 31, in build_package
    pkg.build()
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/packages/python.py", line 42, in build
    self.run(['make'])
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/package.py", line 107, in run
    self.source.run_in_source_dir(cmd)
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/source.py", line 60, in run_in_source_dir
    return self._run_in_dir(cmd, self.source_dir, env, mode)
  File "/home/chillaranand/projects/moriarty/tmp/python3-android/pybuild/source.py", line 52, in _run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/home/chillaranand/.pyenv/versions/3.7-dev/lib/python3.7/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

Turns out both SRE magics are different. Any help on how to fix this?

```
20140917 20170530
```

**Comment by yan12125** [comment]
CPython updated its _sre module recently. Could you rebuild your host CPython 3.7 and try again?

**Comment by ChillarAnand** [comment]
Yes. It built successfully. Thanks, @yan12125. 

Any plans on adding pip support?

**Comment by yan12125** [comment]
Cool :)

> Any plans on adding pip support?

A CPython bug prevents ensurepip from working with cross-builds. I haven't had time to find a solution yet. I'll post updates to #3.
