### ISSUE TITLE
Patch failing

### ISSUE THREAD

**Issue by ssspeq** [yan12125/python3-android#28]
I am trying to build this so that I can build pyotherside using the resulting python but patch fails. Am I doing something obviously wrong?

python -m pybuild
Running in src/cpython: git rev-list --count HEAD
Running in src/cpython: git rev-parse --short HEAD
INFO:pybuild.main:Building python 3.9.0a0.r106518.efc28bbbee
Running in src/cpython: git fetch --no-tags origin master
Från https://github.com/python/cpython
 * branch                  master     -> FETCH_HEAD
Running in src/cpython: git merge --ff-only origin/master
Redan à jour.
Running in src/cpython: git checkout master
Redan på "master"
Din gren är à jour med "origin/master".
Running in src/cpython: git reset .
Running in src/cpython: git checkout .
Running in src/cpython: patch --fuzz=0 --strip=1 --input /home/per/build/python3-android/python3-android/mk/python/cppflags.patch
patching file setup.py
Hunk #1 FAILED at 262.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
Traceback (most recent call last):
  File "/home/per/.pyenv/versions/3.9-dev/lib/python3.9/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/per/.pyenv/versions/3.9-dev/lib/python3.9/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/per/build/python3-android/python3-android/pybuild/__main__.py", line 3, in <module>
    main()
  File "/home/per/build/python3-android/python3-android/pybuild/main.py", line 42, in main
    build_package('python')
  File "/home/per/build/python3-android/python3-android/pybuild/main.py", line 29, in build_package
    patch.apply(pkg.source, pkg)
  File "/home/per/build/python3-android/python3-android/pybuild/patch.py", line 21, in apply
    self.apply_file(package.filesdir / self.name, source)
  File "/home/per/build/python3-android/python3-android/pybuild/patch.py", line 15, in apply_file
    source.run_in_source_dir([
  File "/home/per/build/python3-android/python3-android/pybuild/source.py", line 52, in run_in_source_dir
    return run_in_dir(cmd, self.source_dir, env, mode)
  File "/home/per/build/python3-android/python3-android/pybuild/util.py", line 65, in run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/home/per/.pyenv/versions/3.9-dev/lib/python3.9/subprocess.py", line 372, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '--fuzz=0', '--strip=1', '--input', '/home/per/build/python3-android/python3-android/mk/python/cppflags.patch']' returned non-zero exit status 1.
make: *** [Makefile:4: all] Fel 1

**Comment by ssspeq** [comment]
Oops, sorry about the swedish language, perhaps you can make it out anyway.

**Comment by mkalinowski2** [comment]
Hi, I have same issue when I try build from docker:
sudo docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/python3-android python3-android-base
[sudo] password for viader: 
gpg: directory '/python3-android/.gnupg' created
gpg: keybox '/python3-android/.gnupg/pubring.kbx' created
gpg: key 3602B07F55D0C732: 55 signatures not checked due to missing keys
gpg: /python3-android/.gnupg/trustdb.gpg: trustdb created
gpg: key 3602B07F55D0C732: public key "Sergey Poznyakoff <gray@gnu.org>" imported
gpg: key 702353E0F7E48EDB: 143 signatures not checked due to missing keys
gpg: key 702353E0F7E48EDB: public key "Thomas Dickey <dickey@invisible-island.net>" imported
gpg: key BB5869F064EA74AB: 9 signatures not checked due to missing keys
gpg: key BB5869F064EA74AB: public key "Chet Ramey <chet@cwru.edu>" imported
gpg: key 2DB5BD89A340AEB7: 15 signatures not checked due to missing keys
gpg: key 2DB5BD89A340AEB7: public key "Dmitry V. Levin <ldv@altlinux.org>" imported
gpg: key 3FDDD575826C5C30: public key "Chih-Hsuan Yen <yan16037741@hotmail.com.tw>" imported
gpg: Total number processed: 5
gpg:               imported: 5
gpg: no ultimately trusted keys found
python3.9 -m pybuild
Running in src/cpython: git rev-list --count HEAD
Running in src/cpython: git rev-parse --short HEAD
INFO:pybuild.main:Building python 3.9.0a0.r106640.6ff79f6582
Running in src/cpython: git fetch --no-tags origin master
From https://github.com/python/cpython
 * branch                  master     -> FETCH_HEAD
Running in src/cpython: git merge --ff-only origin/master
Already up to date.
Running in src/cpython: git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
Running in src/cpython: git reset .
Running in src/cpython: git checkout .
Updated 0 paths from the index
Running in src/cpython: patch --fuzz=0 --strip=1 --input /python3-android/mk/python/cppflags.patch
patching file setup.py
Hunk #1 FAILED at 262.
1 out of 1 hunk FAILED -- saving rejects to file setup.py.rej
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/python3-android/pybuild/__main__.py", line 3, in <module>
    main()
  File "/python3-android/pybuild/main.py", line 42, in main
    build_package('python')
  File "/python3-android/pybuild/main.py", line 29, in build_package
    patch.apply(pkg.source, pkg)
  File "/python3-android/pybuild/patch.py", line 21, in apply
    self.apply_file(package.filesdir / self.name, source)
  File "/python3-android/pybuild/patch.py", line 15, in apply_file
    source.run_in_source_dir([
  File "/python3-android/pybuild/source.py", line 52, in run_in_source_dir
    return run_in_dir(cmd, self.source_dir, env, mode)
  File "/python3-android/pybuild/util.py", line 65, in run_in_dir
    check_call(cmd, cwd=cwd, env=real_env)
  File "/usr/lib/python3.9/subprocess.py", line 372, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['patch', '--fuzz=0', '--strip=1', '--input', '/python3-android/mk/python/cppflags.patch']' returned non-zero exit status 1.
make: *** [Makefile:4: all] Error 1

**Comment by yan12125** [comment]
Sorry for the long delay. It should build now.

**Comment by mkalinowski2** [comment]
It works for me now. Thanks!
